spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ayang0422/spring-config-demo
          default-label: master

server:
  port: 1201
